<?php

namespace Database\Seeds\InitData;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminPermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('admin_permissions')->delete();

        DB::table('admin_permissions')->insert(array(
            0 =>
            array(
                'id' => 1,
                'name' => '系统',
                'slug' => 'auth-management',
                'http_method' => '',
                'http_path' => '',
                'order' => 2,
                'parent_id' => 0,
                'created_at' => '2020-06-17 18:04:54',
                'updated_at' => '2021-05-18 10:50:58',
            ),
            1 =>
            array(
                'id' => 2,
                'name' => '管理员',
                'slug' => 'users',
                'http_method' => '',
                'http_path' => '/auth/users*',
                'order' => 3,
                'parent_id' => 1,
                'created_at' => '2020-06-17 18:04:54',
                'updated_at' => '2021-05-18 11:51:38',
            ),
            2 =>
            array(
                'id' => 3,
                'name' => '角色',
                'slug' => 'roles',
                'http_method' => '',
                'http_path' => '/auth/roles*',
                'order' => 4,
                'parent_id' => 1,
                'created_at' => '2020-06-17 18:04:54',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            3 =>
            array(
                'id' => 4,
                'name' => '权限',
                'slug' => 'permissions',
                'http_method' => '',
                'http_path' => '/auth/permissions*',
                'order' => 5,
                'parent_id' => 1,
                'created_at' => '2020-06-17 18:04:54',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            4 =>
            array(
                'id' => 5,
                'name' => '菜单',
                'slug' => 'menu',
                'http_method' => '',
                'http_path' => '/auth/menu*',
                'order' => 6,
                'parent_id' => 1,
                'created_at' => '2020-06-17 18:04:54',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            5 =>
            array(
                'id' => 6,
                'name' => '操作日志',
                'slug' => 'operation-log',
                'http_method' => '',
                'http_path' => '/auth/logs*',
                'order' => 7,
                'parent_id' => 1,
                'created_at' => '2020-06-17 18:04:54',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            6 =>
            array(
                'id' => 7,
                'name' => '文章管理',
                'slug' => 'article',
                'http_method' => '',
                'http_path' => '',
                'order' => 40,
                'parent_id' => 0,
                'created_at' => '2020-09-02 16:45:20',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            7 =>
            array(
                'id' => 8,
                'name' => '文章列表',
                'slug' => 'article-list',
                'http_method' => '',
                'http_path' => '/article*',
                'order' => 41,
                'parent_id' => 7,
                'created_at' => '2020-09-02 16:46:16',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            8 =>
            array(
                'id' => 9,
                'name' => '文章分类',
                'slug' => 'article-category',
                'http_method' => '',
                'http_path' => '/article-category*',
                'order' => 42,
                'parent_id' => 7,
                'created_at' => '2020-09-02 16:46:51',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            9 =>
            array(
                'id' => 10,
                'name' => '用户管理',
                'slug' => 'user-management',
                'http_method' => '',
                'http_path' => '',
                'order' => 8,
                'parent_id' => 0,
                'created_at' => '2020-09-02 17:36:25',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            10 =>
            array(
                'id' => 11,
                'name' => '用户列表',
                'slug' => 'user-list',
                'http_method' => '',
                'http_path' => '/users*',
                'order' => 9,
                'parent_id' => 10,
                'created_at' => '2020-09-02 17:36:51',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            11 =>
            array(
                'id' => 12,
                'name' => '实名认证',
                'slug' => 'user-auth',
                'http_method' => '',
                'http_path' => '/user-auth*',
                'order' => 10,
                'parent_id' => 10,
                'created_at' => '2020-09-02 17:37:22',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            12 =>
            array(
                'id' => 13,
                'name' => '用户级别',
                'slug' => 'user-grade',
                'http_method' => '',
                'http_path' => '/user-grade*',
                'order' => 11,
                'parent_id' => 10,
                'created_at' => '2020-09-02 17:37:48',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            13 =>
            array(
                'id' => 14,
                'name' => '代理管理',
                'slug' => 'agent',
                'http_method' => '',
                'http_path' => '',
                'order' => 14,
                'parent_id' => 0,
                'created_at' => '2020-09-02 17:38:12',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            14 =>
            array(
                'id' => 15,
                'name' => '代理列表',
                'slug' => 'agent-list',
                'http_method' => '',
                'http_path' => '/Agent*',
                'order' => 15,
                'parent_id' => 14,
                'created_at' => '2020-09-02 17:38:35',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            15 =>
            array(
                'id' => 16,
                'name' => '财务管理',
                'slug' => 'finance',
                'http_method' => '',
                'http_path' => '',
                'order' => 16,
                'parent_id' => 0,
                'created_at' => '2020-09-02 17:39:16',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            16 =>
            array(
                'id' => 17,
                'name' => '充币记录',
                'slug' => 'recharge',
                'http_method' => '',
                'http_path' => '/recharge*',
                'order' => 17,
                'parent_id' => 16,
                'created_at' => '2020-09-02 17:41:06',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            17 =>
            array(
                'id' => 18,
                'name' => '提币审核',
                'slug' => 'withdraw',
                'http_method' => '',
                'http_path' => '/withdraw*',
                'order' => 18,
                'parent_id' => 16,
                'created_at' => '2020-09-02 17:41:44',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            18 =>
            array(
                'id' => 19,
                'name' => '划转记录',
                'slug' => 'transfer',
                'http_method' => '',
                'http_path' => '/asset-details*',
                'order' => 19,
                'parent_id' => 16,
                'created_at' => '2020-09-02 17:55:22',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            19 =>
            array(
                'id' => 20,
                'name' => '资产明细',
                'slug' => 'wallet-logs',
                'http_method' => '',
                'http_path' => '/user-wallet-log*',
                'order' => 20,
                'parent_id' => 16,
                'created_at' => '2020-09-02 17:56:49',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            20 =>
            array(
                'id' => 21,
                'name' => '用户资产',
                'slug' => 'user-wallet',
                'http_method' => '',
                'http_path' => '/user-assets*',
                'order' => 21,
                'parent_id' => 16,
                'created_at' => '2020-09-02 17:58:20',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            21 =>
            array(
                'id' => 22,
                'name' => '币种列表',
                'slug' => 'coins',
                'http_method' => '',
                'http_path' => '/coin*',
                'order' => 22,
                'parent_id' => 16,
                'created_at' => '2020-09-02 17:59:01',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            22 =>
            array(
                'id' => 24,
                'name' => '币币交易',
                'slug' => 'exchange',
                'http_method' => '',
                'http_path' => '',
                'order' => 23,
                'parent_id' => 0,
                'created_at' => '2020-09-15 13:40:54',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            23 =>
            array(
                'id' => 25,
                'name' => '买入委托',
                'slug' => 'tradeBuy',
                'http_method' => '',
                'http_path' => '/inside-trade-buy*',
                'order' => 24,
                'parent_id' => 24,
                'created_at' => '2020-09-15 13:41:40',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            24 =>
            array(
                'id' => 26,
                'name' => '卖出委托',
                'slug' => 'tradeSell',
                'http_method' => '',
                'http_path' => '/inside-trade-sell*',
                'order' => 25,
                'parent_id' => 24,
                'created_at' => '2020-09-15 13:42:13',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            25 =>
            array(
                'id' => 27,
                'name' => '成交记录',
                'slug' => 'tradeOrder',
                'http_method' => '',
                'http_path' => '/inside-trade-order*',
                'order' => 26,
                'parent_id' => 24,
                'created_at' => '2020-09-15 13:42:44',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            26 =>
            array(
                'id' => 28,
                'name' => '交易对',
                'slug' => 'tradePair',
                'http_method' => '',
                'http_path' => '/inside-trade-pair*',
                'order' => 27,
                'parent_id' => 24,
                'created_at' => '2020-09-15 13:43:08',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            27 =>
            array(
                'id' => 29,
                'name' => '期权交易',
                'slug' => 'option',
                'http_method' => '',
                'http_path' => '',
                'order' => 28,
                'parent_id' => 0,
                'created_at' => '2020-09-15 13:43:26',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            28 =>
            array(
                'id' => 30,
                'name' => '期权交易对',
                'slug' => 'option-pair',
                'http_method' => '',
                'http_path' => '/option-pair*',
                'order' => 29,
                'parent_id' => 29,
                'created_at' => '2020-09-15 13:44:05',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            29 =>
            array(
                'id' => 31,
                'name' => '周期',
                'slug' => 'option-times',
                'http_method' => '',
                'http_path' => '/option-time*',
                'order' => 30,
                'parent_id' => 29,
                'created_at' => '2020-09-15 13:44:31',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            30 =>
            array(
                'id' => 32,
                'name' => '期权订单',
                'slug' => 'option-order',
                'http_method' => '',
                'http_path' => '/option-order*',
                'order' => 31,
                'parent_id' => 29,
                'created_at' => '2020-09-15 13:44:54',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            31 =>
            array(
                'id' => 33,
                'name' => '期权场景',
                'slug' => 'option-scene',
                'http_method' => '',
                'http_path' => '/option-scene*',
                'order' => 32,
                'parent_id' => 29,
                'created_at' => '2020-09-15 13:45:18',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            32 =>
            array(
                'id' => 34,
                'name' => '永续合约',
                'slug' => 'contract',
                'http_method' => '',
                'http_path' => '',
                'order' => 33,
                'parent_id' => 0,
                'created_at' => '2020-09-15 13:45:53',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            33 =>
            array(
                'id' => 35,
                'name' => '申购管理',
                'slug' => 'subscription',
                'http_method' => '',
                'http_path' => '',
                'order' => 43,
                'parent_id' => 0,
                'created_at' => '2020-09-15 13:47:11',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            34 =>
            array(
                'id' => 36,
                'name' => '申购中',
                'slug' => 'subscription-management',
                'http_method' => '',
                'http_path' => '/subscription-Management*',
                'order' => 44,
                'parent_id' => 35,
                'created_at' => '2020-09-15 13:48:18',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            35 =>
            array(
                'id' => 37,
                'name' => '申购记录',
                'slug' => 'subscribe-record',
                'http_method' => '',
                'http_path' => '/subscribe-record*',
                'order' => 45,
                'parent_id' => 35,
                'created_at' => '2020-09-15 13:49:11',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            36 =>
            array(
                'id' => 38,
                'name' => '首页管理',
                'slug' => 'index-management',
                'http_method' => '',
                'http_path' => '',
                'order' => 46,
                'parent_id' => 0,
                'created_at' => '2020-09-15 13:50:04',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            37 =>
            array(
                'id' => 39,
                'name' => '联系我们',
                'slug' => 'advices',
                'http_method' => '',
                'http_path' => '/advice*',
                'order' => 47,
                'parent_id' => 38,
                'created_at' => '2020-09-15 13:50:28',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            38 =>
            array(
                'id' => 40,
                'name' => '轮播图管理',
                'slug' => 'banners',
                'http_method' => '',
                'http_path' => '/banner*',
                'order' => 48,
                'parent_id' => 38,
                'created_at' => '2020-09-15 13:51:57',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            39 =>
            array(
                'id' => 41,
                'name' => '配置管理',
                'slug' => 'setting',
                'http_method' => '',
                'http_path' => '',
                'order' => 50,
                'parent_id' => 0,
                'created_at' => '2020-09-15 13:52:56',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            40 =>
            array(
                'id' => 42,
                'name' => '通用配置',
                'slug' => 'admin-setting',
                'http_method' => '',
                'http_path' => '/admin-setting*',
                'order' => 51,
                'parent_id' => 41,
                'created_at' => '2020-09-15 13:53:32',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            41 =>
            array(
                'id' => 43,
                'name' => '联系我们信息',
                'slug' => 'contact',
                'http_method' => '',
                'http_path' => '/Contact*',
                'order' => 52,
                'parent_id' => 41,
                'created_at' => '2020-09-15 13:55:13',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            42 =>
            array(
                'id' => 44,
                'name' => '导航栏配置',
                'slug' => 'navigate',
                'http_method' => '',
                'http_path' => '/navigate*',
                'order' => 53,
                'parent_id' => 41,
                'created_at' => '2020-09-15 13:56:05',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            43 =>
            array(
                'id' => 45,
                'name' => 'APP版本',
                'slug' => 'app-version',
                'http_method' => '',
                'http_path' => '/app-version*',
                'order' => 54,
                'parent_id' => 41,
                'created_at' => '2020-09-15 13:56:32',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            44 =>
            array(
                'id' => 46,
                'name' => '咨询项目',
                'slug' => 'enquiries',
                'http_method' => '',
                'http_path' => '/enquiries*',
                'order' => 49,
                'parent_id' => 38,
                'created_at' => '2020-09-15 13:57:30',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            45 =>
            array(
                'id' => 47,
                'name' => '充值',
                'slug' => 'user-recharge',
                'http_method' => '',
                'http_path' => '',
                'order' => 12,
                'parent_id' => 10,
                'created_at' => '2020-09-15 14:58:09',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            46 =>
            array(
                'id' => 48,
                'name' => '新增系统用户',
                'slug' => 'addSystemUser',
                'http_method' => '',
                'http_path' => '',
                'order' => 13,
                'parent_id' => 10,
                'created_at' => '2020-09-15 14:59:53',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            47 =>
            array(
                'id' => 49,
                'name' => '合约列表',
                'slug' => 'contract-pair',
                'http_method' => '',
                'http_path' => '/contract-pair*',
                'order' => 34,
                'parent_id' => 34,
                'created_at' => '2020-11-12 10:55:02',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            48 =>
            array(
                'id' => 50,
                'name' => '合约委托',
                'slug' => 'contract-entrust',
                'http_method' => '',
                'http_path' => '/contract-entrust*',
                'order' => 35,
                'parent_id' => 34,
                'created_at' => '2020-11-12 10:55:54',
                'updated_at' => '2021-05-18 09:58:46',
            ),
            49 =>
            array(
                'id' => 51,
                'name' => '成交记录',
                'slug' => 'contract-order',
                'http_method' => '',
                'http_path' => '/contract-order*',
                'order' => 36,
                'parent_id' => 34,
                'created_at' => '2020-11-12 10:56:37',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            50 =>
            array(
                'id' => 52,
                'name' => '合约持仓',
                'slug' => 'contract-position',
                'http_method' => '',
                'http_path' => '/contract-position*',
                'order' => 37,
                'parent_id' => 34,
                'created_at' => '2020-11-12 10:57:18',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            51 =>
            array(
                'id' => 53,
                'name' => '穿仓记录',
                'slug' => 'contract-wear-position-record',
                'http_method' => '',
                'http_path' => '/contract-wear-position-record*',
                'order' => 38,
                'parent_id' => 34,
                'created_at' => '2020-11-12 10:58:01',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            52 =>
            array(
                'id' => 54,
                'name' => '合约账户',
                'slug' => 'contract-account',
                'http_method' => '',
                'http_path' => '/contract-account*',
                'order' => 39,
                'parent_id' => 34,
                'created_at' => '2020-11-12 10:58:26',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            53 =>
            array(
                'id' => 55,
                'name' => '钱包管理',
                'slug' => 'wallet',
                'http_method' => '',
                'http_path' => '',
                'order' => 55,
                'parent_id' => 0,
                'created_at' => '2020-11-12 11:00:04',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            54 =>
            array(
                'id' => 56,
                'name' => 'USDT（erc20）',
                'slug' => 'erc20usdt',
                'http_method' => '',
                'http_path' => '/erc20usdt-accounts*',
                'order' => 56,
                'parent_id' => 55,
                'created_at' => '2020-11-12 11:01:05',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            55 =>
            array(
                'id' => 57,
                'name' => 'USDT（omni）',
                'slug' => 'omniusdt',
                'http_method' => '',
                'http_path' => '/omniusdt-accounts*',
                'order' => 57,
                'parent_id' => 55,
                'created_at' => '2020-11-12 11:01:30',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            56 =>
            array(
                'id' => 58,
                'name' => 'ETH',
                'slug' => 'eth',
                'http_method' => '',
                'http_path' => '/eth-accounts*',
                'order' => 58,
                'parent_id' => 55,
                'created_at' => '2020-11-12 11:01:55',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            57 =>
            array(
                'id' => 59,
                'name' => 'BTC',
                'slug' => 'btc',
                'http_method' => '',
                'http_path' => '/btc-accounts*',
                'order' => 59,
                'parent_id' => 55,
                'created_at' => '2020-11-12 11:02:09',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            58 =>
            array(
                'id' => 60,
                'name' => '中心钱包',
                'slug' => 'center-wallet',
                'http_method' => '',
                'http_path' => '/center-wallet*',
                'order' => 60,
                'parent_id' => 55,
                'created_at' => '2020-11-12 11:02:37',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            59 =>
            array(
                'id' => 61,
                'name' => '归集列表',
                'slug' => 'wallet-collection',
                'http_method' => '',
                'http_path' => '/wallet-collection*',
                'order' => 61,
                'parent_id' => 55,
                'created_at' => '2020-11-12 11:03:06',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            60 =>
            array(
                'id' => 62,
                'name' => '主页',
                'slug' => 'Index',
                'http_method' => 'GET',
                'http_path' => '',
                'order' => 1,
                'parent_id' => 0,
                'created_at' => '2020-11-12 11:58:06',
                'updated_at' => '2020-11-12 11:58:44',
            ),
            61 =>
            array(
                'id' => 78,
                'name' => '申购活动',
                'slug' => 'subscribe-activity',
                'http_method' => '',
                'http_path' => '/subscribe-activity*',
                'order' => 77,
                'parent_id' => 35,
                'created_at' => '2021-07-01 11:47:06',
                'updated_at' => '2021-07-01 11:47:06',
            ),
            62 =>
            array(
                'id' => 79,
                'name' => '申购结算',
                'slug' => 'subscribe-settlement',
                'http_method' => '',
                'http_path' => '/subscribe-settlement*',
                'order' => 78,
                'parent_id' => 14,
                'created_at' => '2021-07-03 16:42:27',
                'updated_at' => '2021-07-03 16:42:27',
            ),
            63 =>
            array(
                'id' => 80,
                'name' => '合约结算',
                'slug' => 'contract-settlement',
                'http_method' => '',
                'http_path' => '/contract-settlement*',
                'order' => 79,
                'parent_id' => 14,
                'created_at' => '2021-07-03 16:43:37',
                'updated_at' => '2021-07-03 16:43:37',
            ),
            64 =>
            array(
                'id' => 81,
                'name' => '期权结算',
                'slug' => 'option-settlement',
                'http_method' => '',
                'http_path' => '/option-settlement*',
                'order' => 80,
                'parent_id' => 14,
                'created_at' => '2021-07-04 16:48:37',
                'updated_at' => '2021-07-04 16:48:37',
            ),
            65 =>
            array(
                'id' => 82,
                'name' => '合约分享',
                'slug' => 'contract-share',
                'http_method' => '',
                'http_path' => '/contract-share*',
                'order' => 81,
                'parent_id' => 41,
                'created_at' => '2021-07-12 13:13:37',
                'updated_at' => '2021-07-12 13:13:37',
            ),
            66 =>
            array(
                'id' => 83,
                'name' => '代理业绩',
                'slug' => 'performance',
                'http_method' => '',
                'http_path' => '/performance*',
                'order' => 82,
                'parent_id' => 14,
                'created_at' => '2021-07-12 15:17:33',
                'updated_at' => '2021-07-12 15:17:33',
            ),
            67 =>
            array(
                'id' => 84,
                'name' => '渠道商列表',
                'slug' => 'place',
                'http_method' => '',
                'http_path' => '/place*',
                'order' => 83,
                'parent_id' => 0,
                'created_at' => '2021-08-04 22:32:26',
                'updated_at' => '2021-08-04 22:32:26',
            ),
        ));
    }
}
