<?php

namespace Database\Seeds\InitData;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContractPairTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('contract_pair')->delete();

        DB::table('contract_pair')->insert(array(
            0 =>
            array(
                'id' => 1,
                'symbol' => 'BTC',
                'contract_coin_id' => 2,
                'contract_coin_name' => 'BTC',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:46:59',
                'updated_at' => '2021-04-13 23:46:59',
            ),
            1 =>
            array(
                'id' => 2,
                'symbol' => 'ETH',
                'contract_coin_id' => 3,
                'contract_coin_name' => 'ETH',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:27',
                'updated_at' => '2021-04-13 23:47:27',
            ),
            2 =>
            array(
                'id' => 3,
                'symbol' => 'DOT',
                'contract_coin_id' => 27,
                'contract_coin_name' => 'DOT',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:27',
                'updated_at' => '2021-04-13 23:47:27',
            ),
            3 =>
            array(
                'id' => 4,
                'symbol' => 'FIL',
                'contract_coin_id' => 28,
                'contract_coin_name' => 'FIL',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:37',
                'updated_at' => '2021-04-13 23:47:37',
            ),
            4 =>
            array(
                'id' => 5,
                'symbol' => 'BT',
                'contract_coin_id' => 41,
                'contract_coin_name' => 'BT',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-06-07 19:28:19',
                'updated_at' => '2021-06-07 19:28:19',
            ),
            5 =>
            array(
                'id' => 6,
                'symbol' => 'TKB',
                'contract_coin_id' => 42,
                'contract_coin_name' => 'TKB',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-07-21 19:28:50',
                'updated_at' => '2021-07-21 19:28:50',
            ),
            6 =>
            array(
                'id' => 7,
                'symbol' => 'SUSHI',
                'contract_coin_id' => 31,
                'contract_coin_name' => 'SUSHI',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:39',
                'updated_at' => '2021-04-13 23:47:39',
            ),
            7 =>
            array(
                'id' => 8,
                'symbol' => 'STORJ',
                'contract_coin_id' => 32,
                'contract_coin_name' => 'STORJ',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:40',
                'updated_at' => '2021-04-13 23:47:40',
            ),
            8 =>
            array(
                'id' => 10,
                'symbol' => 'ATOM',
                'contract_coin_id' => 19,
                'contract_coin_name' => 'ATOM',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:41',
                'updated_at' => '2021-04-13 23:47:41',
            ),
            9 =>
            array(
                'id' => 11,
                'symbol' => 'BCH',
                'contract_coin_id' => 8,
                'contract_coin_name' => 'BCH',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "200", "100"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:04',
                'updated_at' => '2021-04-13 23:47:04',
            ),
            10 =>
            array(
                'id' => 12,
                'symbol' => 'BSV',
                'contract_coin_id' => 9,
                'contract_coin_name' => 'BSV',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "200", "100"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:04',
                'updated_at' => '2021-04-13 23:47:04',
            ),
            11 =>
            array(
                'id' => 13,
                'symbol' => 'EOS',
                'contract_coin_id' => 4,
                'contract_coin_name' => 'EOS',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "200", "100"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:05',
                'updated_at' => '2021-04-13 23:47:05',
            ),
            12 =>
            array(
                'id' => 14,
                'symbol' => 'ETC',
                'contract_coin_id' => 5,
                'contract_coin_name' => 'ETC',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "200", "100"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:06',
                'updated_at' => '2021-04-13 23:47:06',
            ),
            13 =>
            array(
                'id' => 15,
                'symbol' => 'TRX',
                'contract_coin_id' => 13,
                'contract_coin_name' => 'TRX',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "200", "100"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:06',
                'updated_at' => '2021-04-13 23:47:06',
            ),
            14 =>
            array(
                'id' => 16,
                'symbol' => 'LTC',
                'contract_coin_id' => 11,
                'contract_coin_name' => 'LTC',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:07',
                'updated_at' => '2021-04-13 23:47:07',
            ),
            15 =>
            array(
                'id' => 17,
                'symbol' => 'DASH',
                'contract_coin_id' => 10,
                'contract_coin_name' => 'DASH',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:08',
                'updated_at' => '2021-04-13 23:47:08',
            ),
            16 =>
            array(
                'id' => 18,
                'symbol' => 'XRP',
                'contract_coin_id' => 34,
                'contract_coin_name' => 'XRP',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-04-13 23:47:48',
                'updated_at' => '2021-04-13 23:47:48',
            ),
            17 =>
            array(
                'id' => 25,
                'symbol' => 'UNI',
                'contract_coin_id' => 29,
                'contract_coin_name' => 'UNI',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-06-07 19:28:11',
                'updated_at' => '2021-06-07 19:28:11',
            ),
            18 =>
            array(
                'id' => 26,
                'symbol' => 'YFI',
                'contract_coin_id' => 30,
                'contract_coin_name' => 'YFI',
                'margin_coin_id' => 1,
                'type' => 'USDT',
                'unit_amount' => '1000',
                'maker_fee_rate' => 0.0005,
                'taker_fee_rate' => 0.0005,
                'status' => 1,
                'trade_status' => 1,
                'lever_rage' => '["20", "50", "100", "200"]',
                'default_lever' => '100',
                'min_qty' => 1,
                'max_qty' => 10000,
                'total_max_qty' => 1000000,
                'buy_spread' => '0',
                'sell_spread' => '0',
                'settle_spread' => '0',
                'created_at' => '2021-06-07 19:28:15',
                'updated_at' => '2021-06-07 19:28:15',
            ),
        ));
    }
}
