<?php

namespace Database\Seeds\InitData;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsideTradePairTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('inside_trade_pair')->delete();

        DB::table('inside_trade_pair')->insert(array(
            0 =>
            array(
                'pair_id' => 1,
                'pair_name' => 'BTC/USDT',
                'symbol' => 'btcusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 2,
                'base_coin_name' => 'BTC',
                'qty_decimals' => 6,
                'price_decimals' => 2,
                'min_qty' => '0.0001',
                'min_total' => '10.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 1,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-06-23 12:08:29',
                'updated_at' => '2020-06-23 12:06:50',
            ),
            1 =>
            array(
                'pair_id' => 2,
                'pair_name' => 'ETH/USDT',
                'symbol' => 'ethusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 3,
                'base_coin_name' => 'ETH',
                'qty_decimals' => 4,
                'price_decimals' => 2,
                'min_qty' => '0.0010',
                'min_total' => '10.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 2,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-06-23 12:08:31',
                'updated_at' => '2020-06-23 12:06:55',
            ),
            2 =>
            array(
                'pair_id' => 3,
                'pair_name' => 'EOS/USDT',
                'symbol' => 'eosusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 4,
                'base_coin_name' => 'EOS',
                'qty_decimals' => 4,
                'price_decimals' => 4,
                'min_qty' => '0.1000',
                'min_total' => '10.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 3,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-06-23 12:08:34',
                'updated_at' => '2020-06-23 12:08:38',
            ),
            3 =>
            array(
                'pair_id' => 4,
                'pair_name' => 'ETC/USDT',
                'symbol' => 'etcusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 5,
                'base_coin_name' => 'ETC',
                'qty_decimals' => 4,
                'price_decimals' => 4,
                'min_qty' => '0.0100',
                'min_total' => '10.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 4,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-06-23 12:08:36',
                'updated_at' => '2020-06-23 12:08:41',
            ),
            4 =>
            array(
                'pair_id' => 7,
                'pair_name' => 'ETH/BTC',
                'symbol' => 'ethbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 3,
                'base_coin_name' => 'ETH',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0010',
                'min_total' => '10.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 6,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-06-23 12:08:31',
                'updated_at' => '2020-06-23 12:06:55',
            ),
            5 =>
            array(
                'pair_id' => 8,
                'pair_name' => 'EOS/BTC',
                'symbol' => 'eosbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 4,
                'base_coin_name' => 'EOS',
                'qty_decimals' => 2,
                'price_decimals' => 8,
                'min_qty' => '0.1000',
                'min_total' => '10.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-06-23 12:08:34',
                'updated_at' => '2020-06-23 12:08:38',
            ),
            6 =>
            array(
                'pair_id' => 9,
                'pair_name' => 'ETC/BTC',
                'symbol' => 'etcbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 5,
                'base_coin_name' => 'ETC',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0100',
                'min_total' => '10.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-06-23 12:08:36',
                'updated_at' => '2020-06-23 12:08:41',
            ),
            7 =>
            array(
                'pair_id' => 11,
                'pair_name' => 'XTZ/USDT',
                'symbol' => 'xtzusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 24,
                'base_coin_name' => 'XTZ',
                'qty_decimals' => 4,
                'price_decimals' => 4,
                'min_qty' => '0.0100',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 18:11:14',
                'updated_at' => '2020-07-24 10:07:08',
            ),
            8 =>
            array(
                'pair_id' => 13,
                'pair_name' => 'BHD/USDT',
                'symbol' => 'bhdusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 22,
                'base_coin_name' => 'BHD',
                'qty_decimals' => 4,
                'price_decimals' => 4,
                'min_qty' => '0.0100',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:35:15',
                'updated_at' => '2020-07-24 10:07:09',
            ),
            9 =>
            array(
                'pair_id' => 15,
                'pair_name' => 'WTC/USDT',
                'symbol' => 'wtcusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 20,
                'base_coin_name' => 'WTC',
                'qty_decimals' => 4,
                'price_decimals' => 4,
                'min_qty' => '0.0100',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:35:33',
                'updated_at' => '2021-05-11 11:17:12',
            ),
            10 =>
            array(
                'pair_id' => 16,
                'pair_name' => 'ATOM/USDT',
                'symbol' => 'atomusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 19,
                'base_coin_name' => 'ATOM',
                'qty_decimals' => 2,
                'price_decimals' => 4,
                'min_qty' => '0.0100',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:36:04',
                'updated_at' => '2021-05-11 11:17:14',
            ),
            11 =>
            array(
                'pair_id' => 17,
                'pair_name' => 'LINK/USDT',
                'symbol' => 'linkusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 18,
                'base_coin_name' => 'LINK',
                'qty_decimals' => 2,
                'price_decimals' => 4,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:36:14',
                'updated_at' => '2020-07-24 10:07:14',
            ),
            12 =>
            array(
                'pair_id' => 18,
                'pair_name' => 'IOTA/USDT',
                'symbol' => 'iotausdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 17,
                'base_coin_name' => 'IOTA',
                'qty_decimals' => 4,
                'price_decimals' => 4,
                'min_qty' => '0.0100',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:36:22',
                'updated_at' => '2021-05-11 11:17:15',
            ),
            13 =>
            array(
                'pair_id' => 19,
                'pair_name' => 'DCR/USDT',
                'symbol' => 'dcrusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 16,
                'base_coin_name' => 'DCR',
                'qty_decimals' => 4,
                'price_decimals' => 4,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:36:27',
                'updated_at' => '2020-07-24 10:07:19',
            ),
            14 =>
            array(
                'pair_id' => 20,
                'pair_name' => 'XMR/USDT',
                'symbol' => 'xmrusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 15,
                'base_coin_name' => 'XMR',
                'qty_decimals' => 4,
                'price_decimals' => 2,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:36:35',
                'updated_at' => '2021-05-11 11:17:18',
            ),
            15 =>
            array(
                'pair_id' => 21,
                'pair_name' => 'ADA/USDT',
                'symbol' => 'adausdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 14,
                'base_coin_name' => 'ADA',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:36:42',
                'updated_at' => '2020-07-24 10:07:21',
            ),
            16 =>
            array(
                'pair_id' => 22,
                'pair_name' => 'TRX/USDT',
                'symbol' => 'trxusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 13,
                'base_coin_name' => 'TRX',
                'qty_decimals' => 2,
                'price_decimals' => 6,
                'min_qty' => '1.0000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:36:49',
                'updated_at' => '2020-07-24 10:07:23',
            ),
            17 =>
            array(
                'pair_id' => 23,
                'pair_name' => 'ZEC/USDT',
                'symbol' => 'zecusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 12,
                'base_coin_name' => 'ZEC',
                'qty_decimals' => 4,
                'price_decimals' => 2,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:37:15',
                'updated_at' => '2021-05-11 11:17:19',
            ),
            18 =>
            array(
                'pair_id' => 24,
                'pair_name' => 'LTC/USDT',
                'symbol' => 'ltcusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 11,
                'base_coin_name' => 'LTC',
                'qty_decimals' => 4,
                'price_decimals' => 2,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:38:27',
                'updated_at' => '2020-07-24 10:39:30',
            ),
            19 =>
            array(
                'pair_id' => 25,
                'pair_name' => 'DASH/USDT',
                'symbol' => 'dashusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 10,
                'base_coin_name' => 'DASH',
                'qty_decimals' => 4,
                'price_decimals' => 2,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:38:36',
                'updated_at' => '2020-07-24 10:39:31',
            ),
            20 =>
            array(
                'pair_id' => 26,
                'pair_name' => 'BSV/USDT',
                'symbol' => 'bsvusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 9,
                'base_coin_name' => 'BSV',
                'qty_decimals' => 4,
                'price_decimals' => 4,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:38:41',
                'updated_at' => '2020-07-24 10:39:32',
            ),
            21 =>
            array(
                'pair_id' => 27,
                'pair_name' => 'BCH/USDT',
                'symbol' => 'bchusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 8,
                'base_coin_name' => 'BCH',
                'qty_decimals' => 4,
                'price_decimals' => 2,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:38:47',
                'updated_at' => '2020-07-24 10:39:33',
            ),
            22 =>
            array(
                'pair_id' => 28,
                'pair_name' => 'HT/USDT',
                'symbol' => 'htusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 7,
                'base_coin_name' => 'HT',
                'qty_decimals' => 2,
                'price_decimals' => 4,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 19:38:53',
                'updated_at' => '2021-05-11 11:17:35',
            ),
            23 =>
            array(
                'pair_id' => 30,
                'pair_name' => 'XTZ/BTC',
                'symbol' => 'xtzbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 24,
                'base_coin_name' => 'XTZ',
                'qty_decimals' => 2,
                'price_decimals' => 8,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-20 21:27:03',
                'updated_at' => '2020-07-24 11:10:55',
            ),
            24 =>
            array(
                'pair_id' => 31,
                'pair_name' => 'HT/BTC',
                'symbol' => 'htbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 7,
                'base_coin_name' => 'HT',
                'qty_decimals' => 2,
                'price_decimals' => 8,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:34:38',
                'updated_at' => '2020-07-24 11:10:56',
            ),
            25 =>
            array(
                'pair_id' => 32,
                'pair_name' => 'BCH/BTC',
                'symbol' => 'bchbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 8,
                'base_coin_name' => 'BCH',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:34:57',
                'updated_at' => '2020-07-24 11:11:02',
            ),
            26 =>
            array(
                'pair_id' => 33,
                'pair_name' => 'BSV/BTC',
                'symbol' => 'bsvbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 9,
                'base_coin_name' => 'BSV',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:35:19',
                'updated_at' => '2020-07-24 17:07:29',
            ),
            27 =>
            array(
                'pair_id' => 34,
                'pair_name' => 'DASH/BTC',
                'symbol' => 'dashbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 10,
                'base_coin_name' => 'DASH',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:35:30',
                'updated_at' => '2020-07-24 17:07:28',
            ),
            28 =>
            array(
                'pair_id' => 35,
                'pair_name' => 'LTC/BTC',
                'symbol' => 'ltcbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 11,
                'base_coin_name' => 'LTC',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:42:27',
                'updated_at' => '2020-07-24 17:07:26',
            ),
            29 =>
            array(
                'pair_id' => 36,
                'pair_name' => 'ZEC/BTC',
                'symbol' => 'zecbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 12,
                'base_coin_name' => 'ZEC',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:42:42',
                'updated_at' => '2020-07-24 17:07:23',
            ),
            30 =>
            array(
                'pair_id' => 39,
                'pair_name' => 'XMR/BTC',
                'symbol' => 'xmrbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 15,
                'base_coin_name' => 'XMR',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0001',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:43:11',
                'updated_at' => '2020-07-24 11:18:45',
            ),
            31 =>
            array(
                'pair_id' => 40,
                'pair_name' => 'DCR/BTC',
                'symbol' => 'dcrbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 16,
                'base_coin_name' => 'DCR',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:43:22',
                'updated_at' => '2020-07-24 11:18:41',
            ),
            32 =>
            array(
                'pair_id' => 41,
                'pair_name' => 'IOTA/BTC',
                'symbol' => 'iotabtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 17,
                'base_coin_name' => 'IOTA',
                'qty_decimals' => 2,
                'price_decimals' => 8,
                'min_qty' => '0.0100',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:43:41',
                'updated_at' => '2020-07-24 11:18:40',
            ),
            33 =>
            array(
                'pair_id' => 42,
                'pair_name' => 'ATOM/BTC',
                'symbol' => 'atombtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 19,
                'base_coin_name' => 'ATOM',
                'qty_decimals' => 2,
                'price_decimals' => 8,
                'min_qty' => '0.0100',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:43:52',
                'updated_at' => '2020-07-24 11:18:39',
            ),
            34 =>
            array(
                'pair_id' => 43,
                'pair_name' => 'LINK/BTC',
                'symbol' => 'linkbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 18,
                'base_coin_name' => 'LINK',
                'qty_decimals' => 2,
                'price_decimals' => 8,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:43:59',
                'updated_at' => '2020-07-24 17:10:38',
            ),
            35 =>
            array(
                'pair_id' => 44,
                'pair_name' => 'WTC/BTC',
                'symbol' => 'wtcbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 20,
                'base_coin_name' => 'WTC',
                'qty_decimals' => 2,
                'price_decimals' => 8,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:44:10',
                'updated_at' => '2020-07-24 11:18:37',
            ),
            36 =>
            array(
                'pair_id' => 46,
                'pair_name' => 'BHD/BTC',
                'symbol' => 'bhdbtc',
                'quote_coin_id' => 2,
                'quote_coin_name' => 'BTC',
                'base_coin_id' => 22,
                'base_coin_name' => 'BHD',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.0010',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 1,
                'created_at' => '2020-07-24 10:44:34',
                'updated_at' => '2020-07-24 17:10:22',
            ),
            37 =>
            array(
                'pair_id' => 50,
                'pair_name' => 'XTZ/ETH',
                'symbol' => 'xtzeth',
                'quote_coin_id' => 3,
                'quote_coin_name' => 'ETH',
                'base_coin_id' => 24,
                'base_coin_name' => 'XTZ',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-27 16:43:33',
                'updated_at' => '2020-07-27 16:43:33',
            ),
            38 =>
            array(
                'pair_id' => 51,
                'pair_name' => 'EOS/ETH',
                'symbol' => 'eoseth',
                'quote_coin_id' => 3,
                'quote_coin_name' => 'ETH',
                'base_coin_id' => 4,
                'base_coin_name' => 'EOS',
                'qty_decimals' => 2,
                'price_decimals' => 8,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-27 16:43:54',
                'updated_at' => '2020-07-27 16:43:54',
            ),
            39 =>
            array(
                'pair_id' => 52,
                'pair_name' => 'WTC/ETH',
                'symbol' => 'wtceth',
                'quote_coin_id' => 3,
                'quote_coin_name' => 'ETH',
                'base_coin_id' => 20,
                'base_coin_name' => 'WTC',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '0.1000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2020-07-27 16:44:21',
                'updated_at' => '2020-07-27 16:44:21',
            ),
            40 =>
            array(
                'pair_id' => 53,
                'pair_name' => 'GITP/USDT',
                'symbol' => 'gitpusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 26,
                'base_coin_name' => 'GITP',
                'qty_decimals' => 4,
                'price_decimals' => 5,
                'min_qty' => '1.0000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 9,
                'status' => 1,
                'trade_status' => 0,
                'is_market' => 0,
                'created_at' => '2020-09-04 18:00:28',
                'updated_at' => '2021-05-13 17:22:40',
            ),
            41 =>
            array(
                'pair_id' => 54,
                'pair_name' => 'HT/ETH',
                'symbol' => 'hteth',
                'quote_coin_id' => 3,
                'quote_coin_name' => 'ETH',
                'base_coin_id' => 7,
                'base_coin_name' => 'HT',
                'qty_decimals' => 4,
                'price_decimals' => 6,
                'min_qty' => '1.0000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2021-05-11 09:28:16',
                'updated_at' => '2021-05-11 09:28:38',
            ),
            42 =>
            array(
                'pair_id' => 56,
                'pair_name' => 'DOGE/USDT',
                'symbol' => 'dogeusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 878,
                'base_coin_name' => 'DOGE',
                'qty_decimals' => 4,
                'price_decimals' => 8,
                'min_qty' => '1.0000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2021-05-12 09:28:16',
                'updated_at' => '2021-05-12 09:28:38',
            ),
            43 =>
            array(
                'pair_id' => 57,
                'pair_name' => 'SHIB/USDT',
                'symbol' => 'shibusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 879,
                'base_coin_name' => 'SHIB',
                'qty_decimals' => 4,
                'price_decimals' => 8,
                'min_qty' => '1.0000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 255,
                'status' => 1,
                'trade_status' => 1,
                'is_market' => 1,
                'created_at' => '2021-05-12 09:28:16',
                'updated_at' => '2021-05-12 09:28:38',
            ),
            44 =>
            array(
                'pair_id' => 61,
                'pair_name' => 'BT/USDT',
                'symbol' => 'btusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 41,
                'base_coin_name' => 'BT',
                'qty_decimals' => 4,
                'price_decimals' => 5,
                'min_qty' => '1.0000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 9,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 0,
                'created_at' => '2020-09-04 18:00:28',
                'updated_at' => '2021-05-13 17:22:40',
            ),
            45 =>
            array(
                'pair_id' => 62,
                'pair_name' => 'TKB/USDT',
                'symbol' => 'tkbusdt',
                'quote_coin_id' => 1,
                'quote_coin_name' => 'USDT',
                'base_coin_id' => 42,
                'base_coin_name' => 'TKB',
                'qty_decimals' => 4,
                'price_decimals' => 5,
                'min_qty' => '1.0000',
                'min_total' => '1.0000',
                'trigger_price_buy_rate' => '1.10',
                'trigger_price_sell_rate' => '0.90',
                'sort' => 9,
                'status' => 0,
                'trade_status' => 0,
                'is_market' => 0,
                'created_at' => '2020-09-04 18:00:28',
                'updated_at' => '2021-05-13 17:22:40',
            ),
        ));
    }
}
